# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uygulama.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1091, 843)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1071, 821))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.radioButton = QtWidgets.QRadioButton(self.tab)
        self.radioButton.setGeometry(QtCore.QRect(120, 250, 81, 31))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab)
        self.radioButton_2.setGeometry(QtCore.QRect(240, 250, 81, 31))
        self.radioButton_2.setStyleSheet("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab)
        self.comboBox_4.setGeometry(QtCore.QRect(120, 290, 73, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 290, 81, 21))
        self.label.setObjectName("label")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab)
        self.comboBox_5.setGeometry(QtCore.QRect(240, 290, 73, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(330, 350, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(40, 400, 61, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(50, 600, 55, 16))
        self.label_14.setObjectName("label_14")
        self.textEdit_3 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_3.setGeometry(QtCore.QRect(30, 440, 401, 131))
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_4.setGeometry(QtCore.QRect(30, 640, 401, 131))
        self.textEdit_4.setObjectName("textEdit_4")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_5.setGeometry(QtCore.QRect(520, 440, 401, 131))
        self.textEdit_5.setObjectName("textEdit_5")
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(520, 400, 55, 21))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(540, 600, 55, 16))
        self.label_16.setObjectName("label_16")
        self.textEdit_6 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_6.setGeometry(QtCore.QRect(520, 640, 401, 131))
        self.textEdit_6.setObjectName("textEdit_6")
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(380, 250, 271, 31))
        self.label_17.setObjectName("label_17")
        self.comboBox_6 = QtWidgets.QComboBox(self.tab)
        self.comboBox_6.setGeometry(QtCore.QRect(450, 290, 81, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.label_24 = QtWidgets.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(20, 210, 201, 21))
        self.label_24.setObjectName("label_24")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(690, 10, 361, 181))
        self.groupBox.setObjectName("groupBox")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(60, 70, 101, 31))
        self.label_9.setObjectName("label_9")
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setGeometry(QtCore.QRect(160, 70, 101, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(120, 110, 101, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(30, 150, 131, 21))
        self.label_10.setObjectName("label_10")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_8.setGeometry(QtCore.QRect(20, 30, 121, 20))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_9.setGeometry(QtCore.QRect(170, 30, 141, 20))
        self.radioButton_9.setObjectName("radioButton_9")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 311, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setGeometry(QtCore.QRect(10, 20, 181, 31))
        self.label_12.setObjectName("label_12")
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 50, 271, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(60, 110, 131, 31))
        self.pushButton.setObjectName("pushButton")
        self.comboBox_7 = QtWidgets.QComboBox(self.tab)
        self.comboBox_7.setGeometry(QtCore.QRect(230, 210, 171, 22))
        self.comboBox_7.setObjectName("comboBox_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab)
        self.pushButton_2.setGeometry(QtCore.QRect(950, 740, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(360, 10, 301, 181))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(20, 30, 161, 16))
        self.label_26.setObjectName("label_26")
        self.textEdit_9 = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_9.setGeometry(QtCore.QRect(20, 50, 261, 31))
        self.textEdit_9.setObjectName("textEdit_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_10.setGeometry(QtCore.QRect(100, 110, 93, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label_18 = QtWidgets.QLabel(self.tab_2)
        self.label_18.setGeometry(QtCore.QRect(20, 30, 261, 31))
        self.label_18.setObjectName("label_18")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_3.setGeometry(QtCore.QRect(40, 90, 151, 31))
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_7.setGeometry(QtCore.QRect(440, 110, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_4.setGeometry(QtCore.QRect(40, 140, 81, 31))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_5.setGeometry(QtCore.QRect(250, 90, 101, 31))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_6.setGeometry(QtCore.QRect(250, 140, 101, 31))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_7.setGeometry(QtCore.QRect(90, 180, 191, 41))
        self.radioButton_7.setObjectName("radioButton_7")
        self.label_19 = QtWidgets.QLabel(self.tab_2)
        self.label_19.setGeometry(QtCore.QRect(30, 430, 441, 301))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_2)
        self.label_20.setGeometry(QtCore.QRect(500, 430, 491, 301))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_2)
        self.label_21.setGeometry(QtCore.QRect(20, 240, 151, 21))
        self.label_21.setObjectName("label_21")
        self.textEdit_7 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_7.setGeometry(QtCore.QRect(190, 240, 91, 21))
        self.textEdit_7.setObjectName("textEdit_7")
        self.label_22 = QtWidgets.QLabel(self.tab_2)
        self.label_22.setGeometry(QtCore.QRect(30, 320, 121, 21))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(480, 320, 81, 16))
        self.label_23.setObjectName("label_23")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(580, 50, 121, 31))
        self.label_25.setObjectName("label_25")
        self.textEdit_8 = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit_8.setGeometry(QtCore.QRect(580, 80, 451, 211))
        self.textEdit_8.setObjectName("textEdit_8")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_5.setGeometry(QtCore.QRect(830, 20, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_8.setGeometry(QtCore.QRect(940, 20, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(10, 420, 461, 341))
        self.label_6.setObjectName("label_6")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(10, 40, 111, 31))
        self.label_11.setObjectName("label_11")
        self.textEdit = QtWidgets.QTextEdit(self.tab_3)
        self.textEdit.setGeometry(QtCore.QRect(910, 40, 121, 21))
        self.textEdit.setObjectName("textEdit")
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setGeometry(QtCore.QRect(480, 420, 541, 351))
        self.label_7.setObjectName("label_7")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(830, 40, 71, 21))
        self.label_2.setObjectName("label_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(130, 40, 171, 31))
        self.comboBox_3.setObjectName("comboBox_3")
        self.label_8 = QtWidgets.QLabel(self.tab_3)
        self.label_8.setGeometry(QtCore.QRect(320, 40, 201, 31))
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_3.setGeometry(QtCore.QRect(720, 40, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(500, 140, 521, 281))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(20, 90, 81, 31))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setGeometry(QtCore.QRect(10, 140, 471, 281))
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.tab_3)
        self.comboBox.setGeometry(QtCore.QRect(530, 40, 161, 31))
        self.comboBox.setObjectName("comboBox")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 10, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.tabWidget.addTab(self.tab_3, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radioButton.setText(_translate("Dialog", "Hold-Out"))
        self.radioButton_2.setText(_translate("Dialog", "K-Fold"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#0000ff;\">Split Seçimi</span></p></body></html>"))
        self.pushButton_6.setText(_translate("Dialog", "APPLY"))
        self.label_13.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">X Train</span></p></body></html>"))
        self.label_14.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">X Test</span></p></body></html>"))
        self.label_15.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Y Train</span></p></body></html>"))
        self.label_16.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic;\">Y Test</span></p></body></html>"))
        self.label_17.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#0000ff;\">K-Fold Görmek İstediğimiz Kesitin Seçimi</span></p></body></html>"))
        self.label_24.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#0000ff;\">Ön İşlem Uygulanacak Klasör</span></p></body></html>"))
        self.groupBox.setTitle(_translate("Dialog", "Renk Dönüşümleri"))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#005500;\">Renk Uzayları</span></p></body></html>"))
        self.pushButton_4.setText(_translate("Dialog", "APPLY"))
        self.label_10.setText(_translate("Dialog", "İşlem tamam mesajı"))
        self.radioButton_8.setText(_translate("Dialog", "Orjinal Veri Seti"))
        self.radioButton_9.setText(_translate("Dialog", "Arttırılmış Veri Seti"))
        self.groupBox_2.setTitle(_translate("Dialog", "Klasör Ekle"))
        self.label_12.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#aa0000;\">İmport Edilen Klasör</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "IMPORT"))
        self.pushButton_2.setText(_translate("Dialog", "ILERI"))
        self.groupBox_3.setTitle(_translate("Dialog", "Veri Arttır"))
        self.label_26.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#005500;\">Veri Arttırılacak Klasör</span></p></body></html>"))
        self.pushButton_10.setText(_translate("Dialog", "VERI ARTTIR"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Preprocess"))
        self.label_18.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#0000ff;\">Model Sınıflandırma Algoritması Seçiniz</span></p></body></html>"))
        self.radioButton_3.setText(_translate("Dialog", "Logistic Regression"))
        self.pushButton_7.setText(_translate("Dialog", "APPLY"))
        self.radioButton_4.setText(_translate("Dialog", "K-NN"))
        self.radioButton_5.setText(_translate("Dialog", " SVM"))
        self.radioButton_6.setText(_translate("Dialog", "Naive Bayes"))
        self.radioButton_7.setText(_translate("Dialog", "Decision Tree Classification"))
        self.label_19.setText(_translate("Dialog", "confusion"))
        self.label_20.setText(_translate("Dialog", "roc"))
        self.label_21.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Algoritmanın Başarısı</span></p></body></html>"))
        self.label_22.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Confusion Matrix</span></p></body></html>"))
        self.label_23.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">ROC Eğrisi</span></p></body></html>"))
        self.label_25.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Tahmin Sonuçları</span></p></body></html>"))
        self.pushButton_5.setText(_translate("Dialog", "GERI"))
        self.pushButton_8.setText(_translate("Dialog", "ILERI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Makine Öğrenmesi Algoritmaları"))
        self.label_6.setText(_translate("Dialog", "matrix"))
        self.label_11.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Eğitilecek Klasör</span></p></body></html>"))
        self.label_7.setText(_translate("Dialog", "roc"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Accuracy</span></p></body></html>"))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600; color:#aa0000;\">Transfer Learning Modeli Seç</span></p></body></html>"))
        self.pushButton_3.setText(_translate("Dialog", "APPLY"))
        self.label_4.setText(_translate("Dialog", "loss"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#0000ff;\">Grafikler</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog", "basarı"))
        self.pushButton_9.setText(_translate("Dialog", "GERI"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Transfer Learning"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

